### ISSUE TITLE
N-terminal modifications should be added according old version of MS2PIP

### ISSUE THREAD

**Issue by tivdnbos** [anasilviacs/rescore#3]
Hi,

Instead of adding a N-terminal modification for ms2pip in rescore.py like this:
`nterm=Acetylation,42.010565,opt`
it should be added in rescore.py like this (according to an older version of MS2PIP):
`ptm=Acetylation,42.010565,opt,N-term`

**Comment by anasilviacs** [comment]
the latest version of MS2PIP is now used, and the modifications are generated based on the config file instead of hard-coded
